package entities;
// Generated Jul 29, 2017 11:37:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bophan generated by hbm2java
 */
public class Bophan  implements java.io.Serializable {


     private int mabp;
     private String tenbp;
     private Set hoadons = new HashSet(0);

    public Bophan() {
    }

	
    public Bophan(int mabp, String tenbp) {
        this.mabp = mabp;
        this.tenbp = tenbp;
    }
    public Bophan(int mabp, String tenbp, Set hoadons) {
       this.mabp = mabp;
       this.tenbp = tenbp;
       this.hoadons = hoadons;
    }
   
    public int getMabp() {
        return this.mabp;
    }
    
    public void setMabp(int mabp) {
        this.mabp = mabp;
    }
    public String getTenbp() {
        return this.tenbp;
    }
    
    public void setTenbp(String tenbp) {
        this.tenbp = tenbp;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


